name: upower
version: 0.99.4-3
summary: UPower Power Source Monitoring daemon
description: |
  UPower is an abstraction for enumerating power devices, listening to
  device events and querying history and statistics. Any application
  or service on the system can access the org.freedesktop.UPower
  service via the system message bus.

  Please find the source code at https://code.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/upower
confinement: strict
grade: stable

slots:
  service:
    interface: upower-observe

plugs:
  client:
    interface: upower-observe

apps:
  upowerd:
    daemon: simple
    command: bin/upowerd.sh
    slots:
      - service
    plugs:
      - hardware-observe
  upower:
    command: bin/upower.sh
    plugs:
      - client

parts:
  common:
    plugin: dump
    source: .
    snap:
      - bin
  upower:
    plugin: autotools

    source: https://git.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/upower
    source-type: git
    # For development you can directly build from the xenial branch if
    # needed. Otherwise use the tag to the latest version which will be
    # used by the published snap.
    source-branch: upower/xenial/0.99.4

    configflags:
      - --prefix=/usr
      - --sysconfdir=/etc
      - --with-historydir=/var/snap/upower/common/history

    build-packages:
      - build-essential
      - autotools-dev
      - gobject-introspection
      - gtk-doc-tools
      - intltool
      - libgirepository1.0-dev
      - libglib2.0-dev
      - libglib2.0-doc
      - libgudev-1.0-dev
      - libimobiledevice-dev
      - libusb-1.0-0-dev
      - pkg-config
      - udev
      - xsltproc

    filesets:
      unwanted:
        # FIXME: Drop when we have the upower-control interface in place
        # - -etc/dbus-1
        - -usr/share/locale
        - -usr/share/man
        - -usr/share/dbus-1
        - -usr/include
        - -lib/systemd
        - -lib/udev

    snap:
      - $unwanted
